---
name: Build ISOs

on:
  schedule:
    - cron: "0 0 1 * *" # 1st of each month
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "iso_files/**"
      - ".github/workflows/build-iso.yml"

env:
  IMAGE_REGISTRY: "ghcr.io/${{ github.repository_owner }}"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}-iso
  cancel-in-progress: true

jobs:
  build-iso:
    name: Build ISO (${{ matrix.image }})
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: read
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: razorfin
            image-ref: ghcr.io/razorfinos-org/razorfin:latest
          - image: razorfin-nvidia-open
            image-ref: ghcr.io/razorfinos-org/razorfin-nvidia-open:latest

    steps:
      - name: Maximize build space
        uses: ublue-os/remove-unwanted-software@cc0becac701cf642c8f0a6613bbdaf5dc36b259e # v9
        with:
          remove-codeql: true

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Build ISO
        uses: ublue-os/titanoboa@main
        id: build
        with:
          image-ref: ${{ matrix.image-ref }}
          iso-dest: ${{ matrix.image }}-live-amd64.iso
          hook-post-rootfs: ${{ github.workspace }}/iso_files/configure_iso.sh

      - name: Generate checksum
        id: checksum
        shell: bash
        run: |
          ISO_UPLOAD_DIR=${{ github.workspace }}/upload
          DEST="${ISO_UPLOAD_DIR}/$(basename ${{ steps.build.outputs.iso-dest }})"
          mkdir -p "${ISO_UPLOAD_DIR}"
          mv "${{ steps.build.outputs.iso-dest }}" "${DEST}"
          sha256sum "${DEST}" > "${DEST}.sha256"
          echo "iso-upload-dir=${ISO_UPLOAD_DIR}" >> "$GITHUB_OUTPUT"

      - name: Upload ISO and checksum to artifacts
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: ${{ matrix.image }}-live-amd64
          path: ${{ steps.checksum.outputs.iso-upload-dir }}
          if-no-files-found: error
          retention-days: 3
          compression-level: 0
          overwrite: true

      - name: Upload ISO and checksum to R2
        if: github.event_name != 'pull_request'
        shell: bash
        env:
          RCLONE_CONFIG_R2_TYPE: s3
          RCLONE_CONFIG_R2_PROVIDER: Cloudflare
          RCLONE_CONFIG_R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          RCLONE_CONFIG_R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          RCLONE_CONFIG_R2_REGION: auto
          RCLONE_CONFIG_R2_ENDPOINT: ${{ secrets.R2_ENDPOINT }}
          SOURCE_DIR: ${{ steps.checksum.outputs.iso-upload-dir }}
        run: |
          sudo apt-get update
          sudo apt-get install -y rclone
          rclone copy "${SOURCE_DIR}" R2:${{ secrets.R2_BUCKET_NAME }}
